---
server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: info

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system-logs
          host: whisper-server
          __path__: /var/log/syslog,/var/log/auth.log

  - job_name: whisper-app
    static_configs:
      - targets:
          - localhost
        labels:
          job: whisper-app
          app: transcription
          host: whisper-server
          __path__: /opt/whisper-app-data/logs/*.log
    pipeline_stages:
      - regex:
          expression: >-
            '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})
            (?P<level>\w+) (?P<message>.*)$'
      - labels:
          level:
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05'

  - job_name: analyzer
    static_configs:
      - targets:
          - localhost
        labels:
          job: analyzer
          app: analysis
          host: whisper-server
          __path__: /opt/analyzer/logs/*.log
    pipeline_stages:
      - regex:
          expression: >-
            '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})
            (?P<level>\w+) (?P<message>.*)$'
      - labels:
          level:
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05'

  - job_name: docker-containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'
      - action: replace
        replacement: '/var/lib/docker/containers/*/*-json.log'
        target_label: '__path__'
    pipeline_stages:
      - json:
          expressions:
            log: log
            stream: stream
            time: time
      - labels:
          stream:
      - timestamp:
          source: time
          format: RFC3339Nano
      - output:
          source: log

  - job_name: generator-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: generator
          app: analyzer
          host: whisper-server
          __path__: /opt/analyzer/logs/generator.log
    pipeline_stages:
      - regex:
          expression: >-
            '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3})
            - (?P<logger>\w+) - (?P<level>\w+) - (?P<message>.*)$'
      - labels:
          level:
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05,000'
