global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'windows-exporter'
    static_configs:
      - targets: ['192.168.1.3:9182']  # Замените на IP Windows-станции
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'whisper-app'
    static_configs:
      - targets: ['whisper-app:8000']  # Будет настроено позже

  - job_name: 'generator-metrics'
    static_configs:
      - targets: ['192.168.1.6:8001']
    scrape_interval: 15s
